# Dataset : https://www.kaggle.com/datasets/moro146/supermarket-eda

# Imports


In [4]:
!pip install numpy pandas

In [5]:
import numpy as np
import pandas as pd

# Q1 
* ## Load the Data
* ## Display the First 5 Entries
* ## Display the Last 5 Entries
* ## View Dataset Information
* ## Generate Descriptive Statistics (Numeric and Categorical Data)

In [26]:
data = pd.read_csv("supermarket.csv")


In [27]:
data.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
0,1,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600
1,2,CA-2017-152156,08/11/2017,11/11/2017,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,Kentucky,42420.0,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400
2,3,CA-2017-138688,12/06/2017,16/06/2017,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,California,90036.0,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200
3,4,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775
4,5,US-2016-108966,11/10/2016,18/10/2016,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,Florida,33311.0,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680


In [28]:
data.tail()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales
9795,9796,CA-2017-125920,21/05/2017,28/05/2017,Standard Class,SH-19975,Sally Hughsby,Corporate,United States,Chicago,Illinois,60610.0,Central,OFF-BI-10003429,Office Supplies,Binders,"Cardinal HOLDit! Binder Insert Strips,Extra St...",3.798
9796,9797,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,OFF-AR-10001374,Office Supplies,Art,"BIC Brite Liner Highlighters, Chisel Tip",10.368
9797,9798,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10004977,Technology,Phones,GE 30524EE4,235.188
9798,9799,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-PH-10000912,Technology,Phones,Anker 24W Portable Micro USB Car Charger,26.376
9799,9800,CA-2016-128608,12/01/2016,17/01/2016,Standard Class,CS-12490,Cindy Schnelling,Corporate,United States,Toledo,Ohio,43615.0,East,TEC-AC-10000487,Technology,Accessories,SanDisk Cruzer 4 GB USB Flash Drive,10.384


In [29]:
data.info

<bound method DataFrame.info of       Row ID        Order ID  Order Date   Ship Date       Ship Mode  \
0          1  CA-2017-152156  08/11/2017  11/11/2017    Second Class   
1          2  CA-2017-152156  08/11/2017  11/11/2017    Second Class   
2          3  CA-2017-138688  12/06/2017  16/06/2017    Second Class   
3          4  US-2016-108966  11/10/2016  18/10/2016  Standard Class   
4          5  US-2016-108966  11/10/2016  18/10/2016  Standard Class   
...      ...             ...         ...         ...             ...   
9795    9796  CA-2017-125920  21/05/2017  28/05/2017  Standard Class   
9796    9797  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   
9797    9798  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   
9798    9799  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   
9799    9800  CA-2016-128608  12/01/2016  17/01/2016  Standard Class   

     Customer ID     Customer Name    Segment        Country             City  \
0       CG-12520      

In [30]:
data.describe()

,Row ID,Postal Code,Sales
count,9800.000000,9789.000000,9800.000000
mean,4900.500000,55273.322403,230.769059
std,2829.160653,32041.223413,626.651875
min,1.000000,1040.000000,0.444000
25%,2450.750000,23223.000000,17.248000
50%,4900.500000,58103.000000,54.490000
75%,7350.250000,90008.000000,210.605000
max,9800.000000,99301.000000,22638.480000


In [31]:
data.describe(include='object')

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name
count,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800,9800
unique,4922,1230,1326,4,793,793,3,1,529,49,4,1861,3,17,1849
top,CA-2018-100111,05/09/2017,26/09/2018,Standard Class,WB-21850,William Brown,Consumer,United States,New York City,California,West,OFF-PA-10001970,Office Supplies,Binders,Staple envelope
freq,14,38,34,5859,35,35,5101,9800,891,1946,3140,19,5909,1492,47


# Q2
* ## Identify and Resolve Duplicate Entries
* ## Detect and Handle Missing Values

In [32]:
data.duplicated().sum()

0

In [33]:
data=data.drop_duplicates()

In [34]:
data.isnull().sum()

Row ID            0
Order ID          0
Order Date        0
Ship Date         0
Ship Mode         0
Customer ID       0
Customer Name     0
Segment           0
Country           0
City              0
State             0
Postal Code      11
Region            0
Product ID        0
Category          0
Sub-Category      0
Product Name      0
Sales             0
dtype: int64

In [37]:
num_col = data.select_dtypes(include=np.number).columns
data[num_col] = data[num_col].fillna(data[num_col].median())

string_col = data.select_dtypes(include='object').columns
data[string_col] = data[string_col].fillna( data[string_col] .mode().iloc[0])

# Q3
* ## Make (Row ID as an index)

In [46]:
data.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'Country', 'City', 'State', 'Postal Code',
       'Region', 'Product ID', 'Category', 'Sub-Category', 'Product Name',
       'Sales'],
      dtype='object')

In [68]:
#data.set_index("Row ID" , inplace=True)


# Q4
* ## Using aggregate function to calculate (Max, Min, Mean) of sales column 

In [48]:
data['Sales'].agg(['max', 'min', 'mean'])

max     22638.480000
min         0.444000
mean      230.769059
Name: Sales, dtype: float64

# Q5
* ## What is the most Category and sub-category saled ?
* ## And Make a Pivot table to Calculate the mean for each Category 
* ## Save the pivot table as an excel sheet

In [54]:
data['Category'].value_counts()


Category
Office Supplies    5909
Furniture          2078
Technology         1813
Name: count, dtype: int64

In [55]:
data['Category'].value_counts().idxmax()

'Office Supplies'

In [58]:
data['Sub-Category'].value_counts().idxmax()

'Binders'

In [ ]:
pivot_table=pd.pivot_table(
    data , 
    values='Sales',
    index='Category',
    aggfunc='mean'
)
pivot_table



,Sales
Category,
Furniture,350.653790
Office Supplies,119.381001
Technology,456.401474


# Q6 
* ## Replace full country names with their abbreviations (e.g., "United States" becomes "US") and rename the column to "The Country.

In [61]:
country_map = {
    "United States":"US",
    "Canada":"CA",
    "Mexico":"MX"
}

In [62]:
data['Country']=data['Country'].replace(country_map)

In [64]:
data.rename(
    columns = {"Country":"The Country"},
    inplace=True
)



data.head

<bound method NDFrame.head of               Order ID  Order Date   Ship Date       Ship Mode Customer ID  \
Row ID                                                                       
1       CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520   
2       CA-2017-152156  08/11/2017  11/11/2017    Second Class    CG-12520   
3       CA-2017-138688  12/06/2017  16/06/2017    Second Class    DV-13045   
4       US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335   
5       US-2016-108966  11/10/2016  18/10/2016  Standard Class    SO-20335   
...                ...         ...         ...             ...         ...   
9796    CA-2017-125920  21/05/2017  28/05/2017  Standard Class    SH-19975   
9797    CA-2016-128608  12/01/2016  17/01/2016  Standard Class    CS-12490   
9798    CA-2016-128608  12/01/2016  17/01/2016  Standard Class    CS-12490   
9799    CA-2016-128608  12/01/2016  17/01/2016  Standard Class    CS-12490   
9800    CA-2016-128608  12/01/2016

# Q7
* ## Calculate the number of shipping days between the "Order Date" and "Ship Date" columns
* ## And calculate the maximum shipping days and the city of it 

In [70]:
data.columns

Index(['Order ID', 'Order Date', 'Ship Date', 'Ship Mode', 'Customer ID',
       'Customer Name', 'Segment', 'The Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales'],
      dtype='object')

In [74]:
data['Order Date']=pd.to_datetime(
    data["Order Date"] ,
    dayfirst=True
)

data['Ship Date'] =pd.to_datetime(
    data['Ship Date'] , 
    dayfirst=True
)

In [77]:
data['Shipping Days'] = (data['Ship Date'] - data['Order Date']).dt.days

In [79]:
max_days = data['Shipping Days'].max()

max_days

7

In [86]:
city=data.loc[data['Shipping Days'].idxmax(),'City']

city


'Fort Lauderdale'

# Q8 (NumPy)
* ## Import the numpy library
* ## Convert the "Sales" column to a 1D NumPy array
* ## Calculate the sum, mean, and standard deviation of this array using NumPy functions

In [91]:
import numpy as np

sales_array = data['Sales'].to_numpy()

sales_array

array([261.96 , 731.94 ,  14.62 , ..., 235.188,  26.376,  10.384])

In [92]:
print("sum = " ,np.sum(sales_array))
print("Mean = " ,np.mean(sales_array))
print("Std = " ,np.std(sales_array))

sum =  2261536.7827000003
Mean =  230.7690594591837
Std =  626.619901988719


# Q9 (NumPy)
* ## Filter the Sales NumPy array to find all sales greater than 1000
* ## How many such high-value sales are there?

In [94]:
high_sales = sales_array[
    sales_array >1000
]

high_sales

array([ 1706.184 ,  1044.63  ,  3083.43  ,  1097.544 ,  1029.95  ,
        1113.024 ,  1951.84  ,  8159.952 ,  1740.06  ,  1188.    ,
        2001.86  ,  1503.25  ,  3347.37  ,  3059.982 ,  2519.958 ,
        1114.4   ,  1038.84  ,  1082.48  ,  3991.98  ,  4355.168 ,
        1043.92  ,  1023.936 ,  1488.424 ,  1799.97  ,  2396.2656,
        1199.976 ,  1004.024 ,  1336.829 ,  1007.979 ,  1272.63  ,
        2735.952 ,  6354.95  ,  2999.95  ,  1126.02  ,  1121.568 ,
        1295.78  ,  1335.68  ,  1199.976 ,  1049.2   ,  7999.98  ,
        1652.94  ,  1199.976 ,  1363.96  ,  1983.968 ,  1298.55  ,
        1399.93  ,  1228.465 ,  1141.47  ,  1242.9   ,  1199.8   ,
        1928.78  ,  1114.272 ,  1007.232 ,  2065.32  ,  3059.982 ,
        1166.92  ,  2715.93  ,  2309.65  ,  1090.782 ,  1618.37  ,
        1267.53  ,  1379.92  ,  1363.96  ,  1113.504 ,  1106.91  ,
        4899.93  ,  1067.94  ,  2244.48  ,  1322.93  ,  1088.792 ,
        1931.958 ,  3610.848 ,  1141.938 ,  1704.56  ,  1099.9

In [95]:
len(high_sales)

462

In [96]:
high_sales.size

462

# Q10 (NumPy)
* ## Create a NumPy array of 10 random integers between 1 and 100
* ## Reshape the array into a 2x5 matrix
* ## Multiply the entire matrix by 5

In [99]:
random_array =np.random.randint(
    1 , 
    101 , 
    10 
)

random_array

array([17, 58, 60, 62, 30, 96, 62, 88, 43, 57])

In [103]:
matrix =random_array.reshape( 2 , 5 )

matrix

array([[17, 58, 60, 62, 30],
       [96, 62, 88, 43, 57]])

In [104]:
matrix * 5

array([[ 85, 290, 300, 310, 150],
       [480, 310, 440, 215, 285]])